name: Build wheels

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-20.04, macOS-10.15]
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Activate OpenMP compiler on macOS
        if: ${{ matrix.os == 'macOS-10.15' }}
        run: |
            brew install llvm libomp
            echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
            echo "LDFLAGS=-L$(brew --prefix llvm)/lib" >> $GITHUB_ENV

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
